<?php Elite_Vaf_Helper_Data::getInstance()->storeFitInSession(); ?>

<script>
 function changeDiv(e){
     var selectedVal = e.options[e.selectedIndex].value;
     var cat = document.getElementById('catSeelct');
     cat.value = selectedVal;
 }    
</script>
<form action="<?=$this->action()?>" method="<?=$this->getMethod()?>" id="<?=$this->formId()?>" name="<?=$this->formId()?>">
	<input type="hidden" id="vafProduct" value="<?=$this->getProductId()?>" />
	<?=$this->proxyValues();?>
	<div class="vaf-search-custom">
		<h2>Shop by Vehicle</h2>
		<input type="hidden" name="category" id="categorySelect" value="?" />
		<input type="hidden" name="cat" id="catSeelct" value="" />
		<?php
			$levels = $this->getLevels();
			$helper = new VF_SearchLevel();
			$displayLevels = $this->getLevels();
			$c =  3;//count( $displayLevels );
			for( $i = 0; $i < $c; $i++ ) {
				$level = $displayLevels[ $i ];
				$prevLevel = ( $i > 0 ) ? $displayLevels[ $i - 1 ] : false; ?>
				<div class="dropdown-element">
					<?php echo str_replace( 'Select Model_', 'Select Model ', $helper->display( $this, $level, $prevLevel ) ); ?>
				</div>
			<?php }
		?>
		<?php if( $this->showSearchButton() ) : ?>
		<div style="display:block !important" class="amfinder-buttons">     		
			<?php if( $this->showClearButton()  ) : ?>
				<!--input type="button" id="vafClear" value="<?=$this->getClearText()?>" /-->
				<a href="/vaf/product/list/?category=&Make=&Model_Series=&Model_Type=" title="Reset" id="vafClear" value="<?=$this->getClearText()?>" name="reset" class="button"><span><span>Reset</span></span></a>
			<?php endif; ?>
			<button style="float: right;" type="submit" title="Go" class="button vafSubmit"><span><span style="font-size: 20px;font-weight: bold;">Go</span></span></button>
			<!--input type="button" value="<?=$this->getSubmitText()?>" class="vafSubmit" /-->
		</div>
                <?php endif; ?>
	</div>
</form>
<!-- start VAF -->
<script src="/skin/adminhtml/default/default/jquery-1.7.1.min.js" type="text/javascript" language="javascript"></script>
<script type="text/javascript" language="javascript">
 jQuery.noConflict();
</script>
<script src="/skin/adminhtml/default/default/jquery.metadata.pack.js" type="text/javascript" language="javascript"></script>
<script src="/skin/adminhtml/default/default/jquery.simplemodal-1.3.min.js" type="text/javascript" language="javascript"></script>
<script src="<?=Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_LINK, isset($_SERVER['HTTPS']) )?>vaf/ajax/js?front=1&loadingStrategy=<?=$this->loadingStrategy()?>&unavailableSelections=<?=$this->unavailableSelections()?>" type="text/javascript" language="javascript"></script>
<link rel="stylesheet" type="text/css" href="/vafStyle.css.php" media="all" />
<!-- end VAF -->
